version: 2
jobs:
 build:
   docker:
    - image: golang:1.6.4
   steps:
    - setup_remote_docker
    - checkout
    - run:
        name: Install Docker client
        command: |
          set -x
          VER="17.03.0-ce"
          curl -L -o /tmp/docker-$VER.tgz https://download.docker.com/linux/static/stable/x86_64/docker-$VER.tgz
          tar -xz -C /tmp -f /tmp/docker-$VER.tgz
          mv /tmp/docker/* /usr/bin
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: docker build -t spaceapi/directory .
    - run: |
        docker tag spaceapi/directory spaceapi/directory:$CIRCLE_SHA1
        docker push spaceapi/directory:$CIRCLE_SHA1
        docker push spaceapi/directory:latest