version: 2
jobs:
 build:
   docker:
    - image: docker:stable
   steps:
    - setup_remote_docker
    - checkout
    - run: docker login -u $DOCKER_USER -p $DOCKER_PASS
    - run: cd api && docker build -t spaceapi/directory-api .
    - run: |
        docker tag spaceapi/directory-api spaceapi/directory-api:$CIRCLE_SHA1
        docker push spaceapi/directory-api:$CIRCLE_SHA1
        docker push spaceapi/directory-api:latest
    - run: cd collector && docker build -t spaceapi/directory-collector .
    - run: |
        docker tag spaceapi/directory-collector spaceapi/directory-collector:$CIRCLE_SHA1
        docker push spaceapi/directory-collector:$CIRCLE_SHA1
        docker push spaceapi/directory-collector:latest

workflows:
  version: 2
  on_push:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master

  # Build every week on Monday at 04:00 am
  weekly:
    triggers:
      - schedule:
          cron: "0 4 * * 1"
          filters:
            branches:
              only:
                - master
    jobs:
      - build
