
on: push

name: build

jobs:
  build:
    name: Build Docker images
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to GitHub Container Registry
      - name: Build directory-api image
        run: |
          cd api
          docker build \
            --no-cache \
            --tag ghcr.io/spaceapi/directory-api \
            --label "org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
            .
      - name: Build directory-collector image
        run: |
          cd collector
          docker build \
            --no-cache \
            --tag ghcr.io/spaceapi/directory-collector \
            --label "org.opencontainers.image.source=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" \
